### PR TITLE
Starting the specific post backend

### PR DESCRIPTION
**Pull request by christianacostac**
Looking to start the specific post backend for showing the specific post details

### CODE REVIEW

**Review by JuanPablo2655 — APPROVED** [review]
LGTM

**Comment by christianacostac** [comment]
This should be the last of the changes in getting the backend of the creating and reading posts, comments, etc. Deleting and updating posts, comments, and communities coming fairly soon.

**Comment by christianacostac** [comment]
Added the link to go to the specific post

**Review by JuanPablo2655 — APPROVED** [review]
LGTM

**Pull request merged**
